import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import Navbar from '../components/shared/Navbar'
import Footer from '../components/shared/Footer'
import { FileText, Users, Shield, AlertTriangle, Heart, Globe } from 'lucide-react'

const sections = [
  {
    icon: Heart,
    title: 'The Spirit of These Terms',
    content: `KAIROS was built for first-generation students who deserve a safe, warm, and genuinely helpful platform. These terms exist not to create legal barriers between you and KAIROS — but to protect you, protect other students, and ensure this space remains what it was built to be.

Please read them. They are written in plain English because you deserve to understand every word.`
  },
  {
    icon: Users,
    title: 'Who Can Use KAIROS',
    content: `KAIROS is open to:
- Students of any age, gender, background, or location
- Anyone seeking guidance on education, scholarships, or career decisions
- Visitors who want to browse stories or ask anonymous questions

You do not need to be a first-generation student to use KAIROS. You do not need to be from India. You do not need to be a girl. KAIROS is for anyone who needs it.

The only restriction: you must be at least 13 years old to create an account. If you are under 18, we encourage you to use KAIROS with awareness and care.`
  },
  {
    icon: Shield,
    title: 'What You Agree To',
    content: `By using KAIROS, you agree to:

- Be honest — use your real situation when seeking guidance so KAI can genuinely help you
- Be kind — treat other students in the community with the same respect you would want
- Be safe — do not share others' personal information without consent
- Be responsible — do not use KAIROS for purposes other than education and personal guidance

You agree NOT to:
- Create fake accounts or impersonate others
- Submit harmful, abusive, or deliberately misleading content
- Attempt to access, disrupt, or damage KAIROS systems
- Use KAIROS to harass, bully, or harm any other person
- Scrape or copy KAIROS content for commercial use`
  },
  {
    icon: FileText,
    title: 'Content You Submit',
    content: `When you submit a story, ask a question, or share feedback on KAIROS, you grant KAIROS permission to display that content on the platform.

Important protections:
- If you choose to submit anonymously, your anonymity will always be respected — we will never connect your identity to anonymous content
- Stories are reviewed before publishing — we will not publish content that could harm you or others
- You can request removal of your submitted content at any time by contacting us
- KAIROS does not claim ownership of your stories or experiences — they remain yours

KAI's responses are generated by AI and are for guidance purposes only. They do not constitute professional legal, medical, financial, or psychological advice. Always consult qualified professionals for decisions that significantly affect your life.`
  },
  {
    icon: AlertTriangle,
    title: 'KAI and AI Limitations',
    content: `KAI is an AI companion, not a human counselor, therapist, doctor, or lawyer.

KAI's responses:
- Are generated by an AI model and may occasionally contain errors
- Are for guidance and support purposes — not professional advice
- Should be verified with official sources for scholarship and government scheme information
- Are not a substitute for professional mental health support

If you are in crisis, please contact a real human. KAIROS will always show you real crisis helpline numbers when you need them.

Scholarship information on KAIROS is sourced from official government portals and verified to the best of our ability. However, always verify deadlines, amounts, and eligibility on the official portal before applying.`
  },
  {
    icon: Globe,
    title: 'Intellectual Property',
    content: `KAIROS — including its name, design, code, KAI character, and all original content — is the intellectual property of Anchal Bisht.

© 2026 KAIROS by Anchal Bisht. All rights reserved.

You may not:
- Copy, reproduce, or distribute KAIROS code or design
- Use the KAIROS name or KAI character for any other purpose
- Create derivative works based on KAIROS without written permission

The scholarship information, government data, and publicly available resources listed on KAIROS belong to their respective government and organizational sources.`
  },
  {
    icon: Shield,
    title: 'Limitation of Liability',
    content: `KAIROS is provided free of charge as a public service platform for educational equity.

To the maximum extent permitted by law, KAIROS and Anchal Bisht shall not be liable for:
- Decisions made based on KAI's guidance
- Scholarship applications that are unsuccessful
- Career choices made using Compass results
- Any indirect or consequential damages arising from use of the platform

KAIROS makes no guarantee that scholarship information is always current. Government deadlines and eligibility criteria change — always verify on official portals.`
  },
  {
    icon: FileText,
    title: 'Changes to These Terms',
    content: `These terms may be updated as KAIROS grows and evolves. When we make significant changes, we will notify users through the platform.

Your continued use of KAIROS after changes are posted constitutes acceptance of the updated terms.

If you ever disagree with our terms, you may delete your account and stop using KAIROS at any time. We will delete all your data upon request.`
  },
  {
    icon: Heart,
    title: 'Contact',
    content: `If you have questions about these terms or anything else:

Email: anchal001bisht@gmail.com
Response time: Within 48 hours

KAIROS was built with care for every student who uses it. If something feels wrong — in the terms, in the platform, in how you were treated — please tell us. We will listen.`
  },
]

export default function TermsPage() {
  return (
    <div className="bg-void-950 min-h-screen overflow-x-hidden">
      <Navbar />

      <section className="pt-32 pb-16 relative">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[400px] h-[400px] rounded-full"
            style={{ background: 'radial-gradient(ellipse, rgba(124,92,252,0.08) 0%, transparent 70%)' }} />
        </div>
        <div className="section relative z-10 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="flex items-center justify-center gap-3 mb-6">
              <div className="w-8 h-px bg-violet-500/30" />
              <span className="text-[10px] tracking-[3px] text-violet-400 uppercase font-semibold">
                Terms of Use
              </span>
              <div className="w-8 h-px bg-violet-500/30" />
            </div>
            <h1 className="font-display font-extrabold text-3xl sm:text-5xl text-ink-100 mb-4">
              Simple rules for a <span className="gradient-text">safe space.</span>
            </h1>
            <p className="text-ink-100/40 text-sm max-w-xl mx-auto leading-relaxed mb-4">
              These terms exist to protect you and every other student using KAIROS.
              Written in plain English. No legal traps.
            </p>
            <p className="text-ink-100/25 text-[11px]">
              Last updated: June 2026 · Effective immediately
            </p>
          </motion.div>
        </div>
      </section>

      <section className="py-16">
        <div className="section max-w-3xl mx-auto">
          <div className="flex flex-col gap-6">
            {sections.map((section, i) => {
              const Icon = section.icon
              return (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: '-60px' }}
                  transition={{ duration: 0.5, delay: i * 0.04 }}
                  className="glass-card rounded-2xl p-6"
                >
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0"
                      style={{ background: 'rgba(155,126,255,0.1)', border: '0.5px solid rgba(155,126,255,0.2)' }}>
                      <Icon size={16} className="text-violet-400" />
                    </div>
                    <h2 className="font-display font-bold text-[16px] text-ink-100/90">
                      {section.title}
                    </h2>
                  </div>
                  <div className="text-[12.5px] text-ink-100/45 leading-[1.9] whitespace-pre-line">
                    {section.content}
                  </div>
                </motion.div>
              )
            })}
          </div>
        </div>
      </section>

      <section className="py-10 border-t border-violet-500/08">
        <div className="section text-center">
          <p className="text-ink-100/20 text-[11px] max-w-lg mx-auto">
            © 2026 KAIROS by Anchal Bisht. All rights reserved.
          </p>
          <Link to="/" className="btn-ghost text-xs py-2 px-6 mt-6 inline-flex">
            ← Back to KAIROS
          </Link>
        </div>
      </section>

      <Footer />
    </div>
  )
}