import mongoose from 'mongoose'
import dotenv from 'dotenv'
import Scholarship from '../models/Scholarship.model.js'
import Story from '../models/Story.model.js'

dotenv.config()

const scholarships = [
  // ==================== ALL INDIA ====================
  {
    title: 'National Scholarship Portal — Central Sector Scheme',
    provider: 'Ministry of Education, Government of India',
    providerType: 'Central Government',
    eligibility: {
      states: ['All India'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 800000,
      courseLevels: ['Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 80,
    },
    amount: 12000,
    amountDesc: '₹12,000 per year for undergraduate students',
    deadline: 'October 31 every year',
    applicationLink: 'https://scholarships.gov.in',
    documentsRequired: [
      'Class 12 marksheet',
      'Income certificate (below ₹8 lakh)',
      'Aadhaar card',
      'Bank account details',
      'Bonafide certificate from college',
    ],
    applicationSteps: [
      'Register on scholarships.gov.in with Aadhaar',
      'Select Central Sector Scheme for College Students',
      'Fill academic and personal details',
      'Upload all required documents',
      'Submit and note application number',
    ],
    tips: [
      'Apply early — portal slows near deadline',
      'Bank account must be linked to Aadhaar',
      'Income certificate from tehsildar office',
      'Marks in Class 12 must be above 80%',
    ],
    description: 'Central Sector Scheme provides financial assistance to meritorious students from low-income families pursuing higher education across India.',
    tags: ['merit', 'income-based', 'undergraduate', 'central-government', 'all-india'],
    isActive: true,
  },
  {
    title: 'AICTE Pragati Scholarship for Girl Students',
    provider: 'All India Council for Technical Education',
    providerType: 'Central Government',
    eligibility: {
      states: ['All India'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 800000,
      courseLevels: ['Undergraduate Technical'],
      genderSpecific: 'Girls Only',
      minMarks: 0,
    },
    amount: 50000,
    amountDesc: '₹50,000 per year for technical education',
    deadline: 'October 15 every year',
    applicationLink: 'https://www.aicte-india.org/bureaus/pragati',
    documentsRequired: [
      'Class 12 marksheet',
      'Income certificate below ₹8 lakh',
      'Admission letter in AICTE-approved institution',
      'Aadhaar card',
      'Bank details',
    ],
    applicationSteps: [
      'Visit AICTE Pragati scholarship portal',
      'Register with details',
      'Confirm college is AICTE-approved',
      'Fill and submit application',
      'Track on portal',
    ],
    tips: [
      'Only for girls in AICTE-approved technical colleges',
      'One of highest amounts for girl students',
      'Maximum 2 girls per family can receive this',
    ],
    description: 'AICTE Pragati scholarship empowers girl students in technical education with ₹50,000 per year.',
    tags: ['girls-only', 'technical', 'engineering', 'high-amount', 'all-india'],
    isActive: true,
  },
  {
    title: 'Post Matric Scholarship for SC Students',
    provider: 'Ministry of Social Justice and Empowerment',
    providerType: 'Central Government',
    eligibility: {
      states: ['All India'],
      categories: ['SC'],
      incomeLimit: 250000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 23000,
    amountDesc: 'Up to ₹23,000 per year including maintenance allowance',
    deadline: 'November 30 every year',
    applicationLink: 'https://scholarships.gov.in',
    documentsRequired: [
      'Caste certificate SC',
      'Income certificate below ₹2.5 lakh',
      'Previous year marksheet',
      'Aadhaar card',
      'Bank account details',
      'Admission letter from college',
    ],
    applicationSteps: [
      'Login to scholarships.gov.in',
      'Select Post Matric Scholarship for SC',
      'Fill personal and academic details',
      'Upload caste and income certificate',
      'Submit application',
    ],
    tips: [
      'No minimum marks required',
      'Amount includes maintenance and tuition fee',
      'Apply through state portal in some states',
    ],
    description: 'One of the largest scholarship schemes for Scheduled Caste students covering Class 11 to PhD level.',
    tags: ['sc', 'post-matric', 'undergraduate', 'central-government', 'all-india'],
    isActive: true,
  },
  {
    title: 'Post Matric Scholarship for ST Students',
    provider: 'Ministry of Tribal Affairs, Government of India',
    providerType: 'Central Government',
    eligibility: {
      states: ['All India'],
      categories: ['ST'],
      incomeLimit: 250000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 23000,
    amountDesc: 'Up to ₹23,000 per year',
    deadline: 'November 30 every year',
    applicationLink: 'https://scholarships.gov.in',
    documentsRequired: [
      'ST caste certificate',
      'Income certificate below ₹2.5 lakh',
      'Marksheet',
      'Aadhaar card',
      'Bank details',
    ],
    applicationSteps: [
      'Visit scholarships.gov.in',
      'Select Post Matric Scholarship for ST',
      'Complete application form',
      'Upload documents',
      'Submit before deadline',
    ],
    tips: [
      'No minimum marks required',
      'Both tuition and maintenance covered',
    ],
    description: 'Post Matric Scholarship for Scheduled Tribe students supporting education from Class 11 onwards.',
    tags: ['st', 'tribal', 'post-matric', 'all-india', 'central-government'],
    isActive: true,
  },
  {
    title: 'OBC Post Matric Scholarship',
    provider: 'Ministry of Social Justice and Empowerment',
    providerType: 'Central Government',
    eligibility: {
      states: ['All India'],
      categories: ['OBC'],
      incomeLimit: 100000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 15000,
    amountDesc: 'Up to ₹15,000 per year',
    deadline: 'November 30 every year',
    applicationLink: 'https://scholarships.gov.in',
    documentsRequired: [
      'OBC non-creamy layer certificate',
      'Income certificate below ₹1 lakh',
      'Marksheet',
      'Aadhaar card',
      'Bank details',
    ],
    applicationSteps: [
      'Register on scholarships.gov.in',
      'Select OBC Post Matric Scholarship',
      'Fill complete form',
      'Upload OBC certificate',
      'Submit before deadline',
    ],
    tips: [
      'Must have OBC non-creamy layer certificate',
      'Income limit is ₹1 lakh — lower than SC/ST',
      'Apply as early as possible',
    ],
    description: 'Post Matric Scholarship for OBC students to support higher education with tuition and maintenance support.',
    tags: ['obc', 'post-matric', 'all-india', 'central-government'],
    isActive: true,
  },
  {
    title: 'Begum Hazrat Mahal National Scholarship',
    provider: 'Maulana Azad Education Foundation',
    providerType: 'Central Government',
    eligibility: {
      states: ['All India'],
      categories: ['Muslim', 'Christian', 'Sikh', 'Buddhist', 'Jain', 'Parsi'],
      incomeLimit: 200000,
      courseLevels: ['Class 9', 'Class 10', 'Class 11', 'Class 12'],
      genderSpecific: 'Girls Only',
      minMarks: 50,
    },
    amount: 10000,
    amountDesc: '₹5,000 to ₹10,000 per year for minority girls',
    deadline: 'September 30 every year',
    applicationLink: 'https://maef.nic.in',
    documentsRequired: [
      'Previous year marksheet',
      'Minority community certificate',
      'Income certificate below ₹2 lakh',
      'Aadhaar card',
      'Bank passbook',
      'School bonafide certificate',
    ],
    applicationSteps: [
      'Visit maef.nic.in',
      'Register with community certificate',
      'Fill application form',
      'Upload documents',
      'Submit before deadline',
    ],
    tips: [
      'Specifically for girls from minority communities',
      'Get minority certificate from District Magistrate',
      'Income limit is ₹2 lakh',
    ],
    description: 'Named after Begum Hazrat Mahal, this scholarship supports girls from minority communities in Class 9-12.',
    tags: ['girls-only', 'minority', 'school', 'all-india'],
    isActive: true,
  },
  {
    title: 'INSPIRE Scholarship — DST',
    provider: 'Department of Science and Technology',
    providerType: 'Central Government',
    eligibility: {
      states: ['All India'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 0,
      courseLevels: ['Undergraduate Science'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 80000,
    amountDesc: '₹80,000 per year — top 1% in board exams',
    deadline: 'December 31 every year',
    applicationLink: 'https://online-inspire.gov.in',
    documentsRequired: [
      'Class 12 marksheet showing top 1%',
      'Admission proof in BSc program',
      'Aadhaar card',
      'Bank details',
    ],
    applicationSteps: [
      'Check if you are in top 1% of state board',
      'Register at online-inspire.gov.in',
      'Upload marksheet and admission proof',
      'Submit application',
    ],
    tips: [
      'Highest amount for science students',
      'Only for Natural and Basic Sciences',
      'No income limit — purely merit based',
    ],
    description: 'INSPIRE scholarship by DST supports brilliant science students with ₹80,000 per year — no income limit.',
    tags: ['merit', 'science', 'high-amount', 'no-income-limit', 'all-india'],
    isActive: true,
  },
  {
    title: 'HDFC Bank Parivartan ECSS Scholarship',
    provider: 'HDFC Bank',
    providerType: 'Private',
    eligibility: {
      states: ['All India'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 250000,
      courseLevels: ['Undergraduate'],
      genderSpecific: 'All',
      minMarks: 55,
    },
    amount: 75000,
    amountDesc: 'Up to ₹75,000 per year',
    deadline: 'August 31 every year',
    applicationLink: 'https://www.buddy4study.com/hdfc-parivartan',
    documentsRequired: [
      'Class 12 marksheet',
      'College admission proof',
      'Income certificate below ₹2.5 lakh',
      'Aadhaar card',
      'Bank account in student name',
    ],
    applicationSteps: [
      'Apply through Buddy4Study portal',
      'Fill complete profile',
      'Upload documents clearly',
      'Submit before deadline',
      'Shortlisted students get interview call',
    ],
    tips: [
      'One of highest corporate scholarship amounts',
      'Interview is friendly — be honest about situation',
      'Apply through Buddy4Study for easier process',
    ],
    description: 'HDFC Parivartan ECSS supports academically bright students from weaker sections with up to ₹75,000.',
    tags: ['corporate', 'high-amount', 'undergraduate', 'all-india'],
    isActive: true,
  },
  {
    title: 'Sitaram Jindal Foundation Scholarship',
    provider: 'Sitaram Jindal Foundation',
    providerType: 'NGO',
    eligibility: {
      states: ['All India'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 250000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate', 'ITI', 'Diploma'],
      genderSpecific: 'All',
      minMarks: 50,
    },
    amount: 24000,
    amountDesc: '₹1,000 to ₹2,000 per month',
    deadline: 'July 31 every year',
    applicationLink: 'https://www.sitaramjindalfoundation.org',
    documentsRequired: [
      'Previous year marksheet',
      'Income certificate',
      'Aadhaar card',
      'Bank details',
      '2 passport photos',
      'Character certificate',
    ],
    applicationSteps: [
      'Download form from website',
      'Fill in capital letters',
      'Attach all documents',
      'Send by post to Foundation office',
      'Wait for verification call',
    ],
    tips: [
      'Monthly payment makes expenses easier',
      'Apply early — limited seats',
      'One of most trusted NGO scholarships',
    ],
    description: 'Sitaram Jindal Foundation provides monthly scholarships to students across India — one of the most trusted NGO scholarships.',
    tags: ['ngo', 'monthly-payment', 'iti', 'diploma', 'all-india'],
    isActive: true,
  },
  {
    title: 'Vidyasaarathi Scholarship Platform',
    provider: 'NSDL e-Governance Infrastructure',
    providerType: 'Private',
    eligibility: {
      states: ['All India'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 600000,
      courseLevels: ['Undergraduate', 'Diploma', 'ITI'],
      genderSpecific: 'All',
      minMarks: 60,
    },
    amount: 25000,
    amountDesc: '₹10,000 to ₹25,000 from multiple companies',
    deadline: 'Rolling applications throughout year',
    applicationLink: 'https://www.vidyasaarathi.co.in',
    documentsRequired: [
      'Class 10 and 12 marksheets',
      'Income certificate',
      'College admission proof',
      'Aadhaar card',
      'Passport size photo',
    ],
    applicationSteps: [
      'Register on vidyasaarathi.co.in',
      'Complete profile fully',
      'Browse available scholarships',
      'Apply to all you qualify for',
      'Check status regularly',
    ],
    tips: [
      'Multiple companies — apply to all you qualify for',
      'Keep profile updated for automatic matching',
      'Rolling deadlines — apply any time',
    ],
    description: 'Vidyasaarathi is a one-stop platform for corporate scholarships from HDFC, Tata, Wipro and more.',
    tags: ['corporate', 'multiple', 'rolling-deadline', 'all-india'],
    isActive: true,
  },

{
    title: 'National Fellowship and Scholarship for Higher Education of ST Students',
    provider: 'Ministry of Tribal Affairs, Government of India',
    providerType: 'Central Government',
    eligibility: {
      states: ['All India'],
      categories: ['ST'],
      incomeLimit: 600000,
      courseLevels: ['Postgraduate', 'MPhil', 'PhD'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 28800,
    amountDesc: '₹28,800 per year for postgraduate ST students',
    deadline: 'October 31 every year',
    applicationLink: 'https://scholarships.gov.in',
    documentsRequired: [
      'ST caste certificate',
      'Income certificate below ₹6 lakh',
      'Aadhaar card',
      'Previous marksheet',
      'Admission proof in PG course',
      'Bank details',
    ],
    applicationSteps: [
      'Register on scholarships.gov.in',
      'Select National Fellowship for ST Students',
      'Fill complete form',
      'Upload all certificates',
      'Submit before October 31',
    ],
    tips: [
      'Income limit is ₹6 lakh — higher than most schemes',
      'Covers PG MPhil and PhD programs',
      'Very good amount for higher education',
    ],
    description: 'National Fellowship provides substantial financial support to ST students pursuing postgraduate and research programs across India.',
    tags: ['st', 'tribal', 'postgraduate', 'phd', 'research', 'all-india'],
    isActive: true,
  },
  {
    title: 'Dr Ambedkar Post Matric Scholarship for OBC Students',
    provider: 'Ministry of Social Justice, Government of India',
    providerType: 'Central Government',
    eligibility: {
      states: ['All India'],
      categories: ['OBC'],
      incomeLimit: 300000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 10000,
    amountDesc: 'Up to ₹10,000 per year for OBC students',
    deadline: 'November 30 every year',
    applicationLink: 'https://scholarships.gov.in',
    documentsRequired: [
      'OBC non-creamy layer certificate',
      'Income certificate below ₹3 lakh',
      'Aadhaar card',
      'Marksheet',
      'Admission proof',
      'Bank details',
    ],
    applicationSteps: [
      'Visit scholarships.gov.in',
      'Select Dr Ambedkar OBC scholarship',
      'Complete registration',
      'Upload OBC certificate',
      'Submit application',
    ],
    tips: [
      'OBC non-creamy layer certificate is mandatory',
      'Income limit ₹3 lakh for this scheme',
      'Apply before November 30 every year',
    ],
    description: 'Dr Ambedkar Post Matric Scholarship specifically for OBC students pursuing education after Class 10 across India.',
    tags: ['obc', 'ambedkar', 'post-matric', 'all-india', 'central-government'],
    isActive: true,
  },
  {
    title: 'National Overseas Scholarship for SC Students',
    provider: 'Ministry of Social Justice, Government of India',
    providerType: 'Central Government',
    eligibility: {
      states: ['All India'],
      categories: ['SC'],
      incomeLimit: 600000,
      courseLevels: ['Postgraduate', 'PhD'],
      genderSpecific: 'All',
      minMarks: 55,
    },
    amount: 1500000,
    amountDesc: 'Up to ₹15 lakh for studying abroad',
    deadline: 'March 31 every year',
    applicationLink: 'https://nosmsje.gov.in',
    documentsRequired: [
      'SC caste certificate',
      'Income certificate below ₹6 lakh',
      'Aadhaar card',
      'Degree certificates',
      'Admission letter from foreign university',
      'Passport',
    ],
    applicationSteps: [
      'Visit nosmsje.gov.in',
      'Register for National Overseas Scholarship',
      'Upload all degree certificates',
      'Provide foreign university admission',
      'Submit complete application',
    ],
    tips: [
      'For studying ABROAD at masters or PhD level',
      'One of the highest value scholarships in India',
      'Very competitive — requires strong academic record',
      'Income below ₹6 lakh per year',
    ],
    description: 'National Overseas Scholarship provides up to ₹15 lakh for SC students to pursue postgraduate or PhD education abroad.',
    tags: ['sc', 'abroad', 'international', 'high-amount', 'phd', 'masters'],
    isActive: true,
  },


  // ==================== UTTAR PRADESH ====================
  {
    title: 'UP Scholarship — Pre Matric (SC/ST/General)',
    provider: 'Social Welfare Department, Government of Uttar Pradesh',
    providerType: 'State Government',
    eligibility: {
      states: ['Uttar Pradesh'],
      categories: ['SC', 'ST', 'General', 'OBC'],
      incomeLimit: 200000,
      courseLevels: ['Class 9', 'Class 10'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 4000,
    amountDesc: 'Up to ₹4,000 per year for Class 9-10 students',
    deadline: 'October 15 every year',
    applicationLink: 'https://scholarship.up.gov.in',
    documentsRequired: [
      'Aadhaar card',
      'Caste certificate',
      'Income certificate',
      'School enrollment certificate',
      'Bank passbook',
      'Passport photo',
    ],
    applicationSteps: [
      'Visit scholarship.up.gov.in',
      'Register as new student',
      'Fill complete form',
      'Upload documents',
      'Submit and save registration number',
      'Get form verified by school',
    ],
    tips: [
      'UP scholarship portal opens every August',
      'Get school verification done before deadline',
      'Keep registration number safe',
      'Check status regularly on portal',
    ],
    description: 'Uttar Pradesh government scholarship for Pre-Matric students from SC, ST, OBC and General categories with income below ₹2 lakh.',
    tags: ['up', 'state', 'pre-matric', 'sc', 'st', 'obc'],
    isActive: true,
  },
  {
    title: 'UP Post Matric Scholarship — General Category',
    provider: 'Social Welfare Department, Government of Uttar Pradesh',
    providerType: 'State Government',
    eligibility: {
      states: ['Uttar Pradesh'],
      categories: ['General', 'OBC'],
      incomeLimit: 200000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 12000,
    amountDesc: 'Up to ₹12,000 per year',
    deadline: 'November 5 every year',
    applicationLink: 'https://scholarship.up.gov.in',
    documentsRequired: [
      'Aadhaar card',
      'Income certificate',
      'Caste certificate',
      'Previous year marksheet',
      'College enrollment certificate',
      'Bank passbook',
    ],
    applicationSteps: [
      'Visit scholarship.up.gov.in',
      'Select Post Matric scholarship',
      'Register and fill complete form',
      'Upload all documents',
      'Get college verification',
      'Submit final form',
    ],
    tips: [
      'Apply in August when portal opens',
      'College verification is mandatory',
      'Renewal students must update details every year',
    ],
    description: 'UP Post Matric Scholarship for General and OBC students pursuing education after Class 10 in Uttar Pradesh.',
    tags: ['up', 'state', 'post-matric', 'general', 'obc'],
    isActive: true,
  },
  {
    title: 'Mukhyamantri Abhyudaya Yojana — UP Free Coaching',
    provider: 'Government of Uttar Pradesh',
    providerType: 'State Government',
    eligibility: {
      states: ['Uttar Pradesh'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 0,
      courseLevels: ['Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 0,
    amountDesc: 'Free coaching for UPSC, JEE, NEET, NDA and other competitive exams',
    deadline: 'Rolling applications',
    applicationLink: 'https://abhyuday.up.gov.in',
    documentsRequired: [
      'Aadhaar card',
      'UP domicile certificate',
      'Educational certificates',
      'Passport photo',
    ],
    applicationSteps: [
      'Visit abhyuday.up.gov.in',
      'Register with Aadhaar',
      'Select exam you want coaching for',
      'Apply for nearest centre',
      'Attend selection process',
    ],
    tips: [
      'Free coaching for UPSC, JEE, NEET, NDA',
      'Available in all UP districts',
      'Online and offline both available',
    ],
    description: 'Mukhyamantri Abhyudaya Yojana provides free coaching for competitive exams to all UP students regardless of income.',
    tags: ['up', 'free-coaching', 'upsc', 'jee', 'neet', 'competitive-exam'],
    isActive: true,
  },

  // ==================== MAHARASHTRA ====================
  {
    title: 'Maharashtra Government Post Matric Scholarship — SC',
    provider: 'Social Justice Department, Government of Maharashtra',
    providerType: 'State Government',
    eligibility: {
      states: ['Maharashtra'],
      categories: ['SC'],
      incomeLimit: 250000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 20000,
    amountDesc: 'Up to ₹20,000 per year including maintenance',
    deadline: 'November 30 every year',
    applicationLink: 'https://mahadbt.maharashtra.gov.in',
    documentsRequired: [
      'SC caste certificate from Maharashtra',
      'Income certificate',
      'Aadhaar card',
      'Domicile certificate of Maharashtra',
      'Marksheet',
      'Bank details',
    ],
    applicationSteps: [
      'Register on mahadbt.maharashtra.gov.in',
      'Complete KYC with Aadhaar',
      'Select appropriate scholarship scheme',
      'Fill and submit application',
      'Upload documents',
    ],
    tips: [
      'MahaDBT is the single portal for all Maharashtra scholarships',
      'Domicile certificate is mandatory',
      'Keep all documents in PDF format under 200KB',
    ],
    description: 'Maharashtra government scholarship for SC students pursuing post-matric education with tuition and maintenance support.',
    tags: ['maharashtra', 'state', 'sc', 'post-matric'],
    isActive: true,
  },
  {
    title: 'Rajarshi Chhatrapati Shahu Maharaj Scholarship — Maharashtra',
    provider: 'Social Justice Department, Maharashtra',
    providerType: 'State Government',
    eligibility: {
      states: ['Maharashtra'],
      categories: ['OBC', 'VJNT', 'SBC'],
      incomeLimit: 800000,
      courseLevels: ['Undergraduate', 'Postgraduate', 'Professional'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 25000,
    amountDesc: 'Up to ₹25,000 per year',
    deadline: 'December 15 every year',
    applicationLink: 'https://mahadbt.maharashtra.gov.in',
    documentsRequired: [
      'OBC/VJNT/SBC certificate',
      'Income certificate below ₹8 lakh',
      'Maharashtra domicile',
      'Aadhaar card',
      'Marksheet',
      'Fee receipt',
    ],
    applicationSteps: [
      'Login to MahaDBT portal',
      'Select Rajarshi Shahu Maharaj scheme',
      'Fill academic details',
      'Upload caste and income certificates',
      'Submit before deadline',
    ],
    tips: [
      'Covers professional courses like engineering and medicine',
      'OBC non-creamy layer certificate needed',
      'Income limit is ₹8 lakh — higher than most schemes',
    ],
    description: 'Named after Rajarshi Chhatrapati Shahu Maharaj, this scholarship supports OBC, VJNT and SBC students in Maharashtra for professional education.',
    tags: ['maharashtra', 'obc', 'professional', 'engineering', 'medical'],
    isActive: true,
  },
  {
    title: 'Swadhar Greh Scheme — Maharashtra Girls',
    provider: 'Women and Child Development Department, Maharashtra',
    providerType: 'State Government',
    eligibility: {
      states: ['Maharashtra'],
      categories: ['SC', 'ST'],
      incomeLimit: 200000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate'],
      genderSpecific: 'Girls Only',
      minMarks: 0,
    },
    amount: 51000,
    amountDesc: '₹51,000 per year including accommodation and food',
    deadline: 'September 30 every year',
    applicationLink: 'https://mahadbt.maharashtra.gov.in',
    documentsRequired: [
      'SC/ST certificate',
      'Income certificate',
      'Domicile certificate',
      'Aadhaar card',
      'Marksheet',
    ],
    applicationSteps: [
      'Apply on MahaDBT portal',
      'Select Swadhar Greh scheme',
      'Provide accommodation details',
      'Upload documents',
      'Submit application',
    ],
    tips: [
      'Covers accommodation food and other expenses',
      'For SC ST girls living away from home for education',
      'Very high amount covering most expenses',
    ],
    description: 'Swadhar Greh provides comprehensive support including accommodation and food for SC/ST girl students in Maharashtra studying away from home.',
    tags: ['maharashtra', 'girls-only', 'sc', 'st', 'accommodation', 'high-amount'],
    isActive: true,
  },

  // ==================== BIHAR ====================
  {
    title: 'Bihar Post Matric Scholarship — SC/ST',
    provider: 'SC/ST Welfare Department, Government of Bihar',
    providerType: 'State Government',
    eligibility: {
      states: ['Bihar'],
      categories: ['SC', 'ST'],
      incomeLimit: 250000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 15000,
    amountDesc: 'Up to ₹15,000 per year',
    deadline: 'October 31 every year',
    applicationLink: 'https://pmsonline.bih.nic.in',
    documentsRequired: [
      'SC/ST caste certificate from Bihar',
      'Income certificate',
      'Aadhaar card',
      'Resident certificate of Bihar',
      'Marksheet',
      'Bank details',
    ],
    applicationSteps: [
      'Visit pmsonline.bih.nic.in',
      'Register as new applicant',
      'Fill scholarship form',
      'Upload documents',
      'Submit for college verification',
    ],
    tips: [
      'Bihar domicile certificate is mandatory',
      'Apply as soon as portal opens in July',
      'Keep application number for tracking',
    ],
    description: 'Bihar government Post Matric Scholarship for SC and ST students pursuing education after Class 10.',
    tags: ['bihar', 'state', 'sc', 'st', 'post-matric'],
    isActive: true,
  },
  {
    title: 'Mukhyamantri Kanya Utthan Yojana — Bihar',
    provider: 'Government of Bihar',
    providerType: 'State Government',
    eligibility: {
      states: ['Bihar'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 0,
      courseLevels: ['Undergraduate'],
      genderSpecific: 'Girls Only',
      minMarks: 0,
    },
    amount: 50000,
    amountDesc: '₹50,000 on graduation completion',
    deadline: 'Apply after graduation',
    applicationLink: 'https://medhasoft.bih.nic.in',
    documentsRequired: [
      'Graduation certificate',
      'Aadhaar card',
      'Bihar domicile',
      'Bank account in own name',
      'Passport photo',
      'Mobile number linked to Aadhaar',
    ],
    applicationSteps: [
      'Visit medhasoft.bih.nic.in',
      'Register with student ID',
      'Fill graduation details',
      'Upload documents',
      'Submit application after graduation',
    ],
    tips: [
      'One time payment of ₹50,000 on graduation',
      'No income limit — for all girls',
      'Must be unmarried at time of graduation',
      'Apply within 1 year of graduation',
    ],
    description: 'Mukhyamantri Kanya Utthan Yojana provides ₹50,000 to every girl who completes graduation in Bihar regardless of income.',
    tags: ['bihar', 'girls-only', 'graduation', 'one-time', 'high-amount', 'no-income-limit'],
    isActive: true,
  },
  {
    title: 'Bihar Student Credit Card Scheme',
    provider: 'Education Department, Government of Bihar',
    providerType: 'State Government',
    eligibility: {
      states: ['Bihar'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 0,
      courseLevels: ['Undergraduate', 'Postgraduate', 'Diploma'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 400000,
    amountDesc: 'Education loan up to ₹4 lakh at 0% interest for girls, 1% for boys',
    deadline: 'Rolling applications',
    applicationLink: 'https://www.7nishchay-yuvaupmission.bihar.gov.in',
    documentsRequired: [
      'Class 12 certificate',
      'Admission letter from college',
      'Aadhaar card',
      'Bihar domicile',
      'Passport photo',
      'Bank details',
    ],
    applicationSteps: [
      'Visit 7nishchay portal',
      'Register for Student Credit Card',
      'Book appointment at DRCC office',
      'Visit with all documents',
      'Complete loan process',
    ],
    tips: [
      'Zero interest for girl students',
      'No collateral needed',
      'Covers fees hostel food and books',
      'Repayment starts after job',
    ],
    description: 'Bihar Student Credit Card provides up to ₹4 lakh education loan at 0% interest for girls and 1% for boys — no collateral needed.',
    tags: ['bihar', 'loan', 'zero-interest', 'girls-benefit', 'high-amount'],
    isActive: true,
  },

  // ==================== RAJASTHAN ====================
  {
    title: 'Rajasthan Post Matric Scholarship — SC/OBC',
    provider: 'Social Justice and Empowerment Department, Rajasthan',
    providerType: 'State Government',
    eligibility: {
      states: ['Rajasthan'],
      categories: ['SC', 'OBC'],
      incomeLimit: 250000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 15000,
    amountDesc: 'Up to ₹15,000 per year',
    deadline: 'December 31 every year',
    applicationLink: 'https://sje.rajasthan.gov.in',
    documentsRequired: [
      'Caste certificate',
      'Income certificate',
      'Rajasthan domicile',
      'Aadhaar card',
      'Marksheet',
      'Bank details',
      'College bonafide certificate',
    ],
    applicationSteps: [
      'Visit sje.rajasthan.gov.in',
      'Register with Aadhaar and Jan Aadhaar',
      'Fill scholarship form',
      'Upload documents',
      'Get college verification',
      'Submit final application',
    ],
    tips: [
      'Jan Aadhaar card is required for Rajasthan scholarships',
      'Apply on SSO Rajasthan portal',
      'College principal must verify application',
    ],
    description: 'Rajasthan Post Matric Scholarship for SC and OBC students with income below ₹2.5 lakh.',
    tags: ['rajasthan', 'state', 'sc', 'obc', 'post-matric'],
    isActive: true,
  },
  {
    title: 'Rajasthan Devnarayan Girl Student Scholarship',
    provider: 'Social Justice Department, Rajasthan',
    providerType: 'State Government',
    eligibility: {
      states: ['Rajasthan'],
      categories: ['OBC'],
      incomeLimit: 200000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'Girls Only',
      minMarks: 50,
    },
    amount: 15000,
    amountDesc: '₹10,000 to ₹15,000 per year for OBC girls',
    deadline: 'November 30 every year',
    applicationLink: 'https://sso.rajasthan.gov.in',
    documentsRequired: [
      'OBC certificate',
      'Income certificate below ₹2 lakh',
      'Rajasthan domicile',
      'Jan Aadhaar card',
      'Marksheet',
      'College bonafide',
    ],
    applicationSteps: [
      'Login to SSO Rajasthan portal',
      'Select Devnarayan scholarship scheme',
      'Fill complete form',
      'Upload all documents',
      'Submit before deadline',
    ],
    tips: [
      'Specifically for OBC girls in Rajasthan',
      'Jan Aadhaar mandatory',
      'Must have scored above 50%',
    ],
    description: 'Devnarayan scholarship specifically supports OBC girl students in Rajasthan pursuing education after Class 10.',
    tags: ['rajasthan', 'obc', 'girls-only', 'post-matric'],
    isActive: true,
  },
  {
    title: 'Rajasthan Ambedkar DNT Scholarship',
    provider: 'Social Justice Department, Rajasthan',
    providerType: 'State Government',
    eligibility: {
      states: ['Rajasthan'],
      categories: ['DNT', 'SC', 'ST'],
      incomeLimit: 250000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 10000,
    amountDesc: 'Up to ₹10,000 per year',
    deadline: 'December 31 every year',
    applicationLink: 'https://sso.rajasthan.gov.in',
    documentsRequired: [
      'DNT/SC/ST certificate',
      'Income certificate',
      'Domicile certificate',
      'Jan Aadhaar card',
      'Marksheet',
    ],
    applicationSteps: [
      'Login to SSO Rajasthan',
      'Select Ambedkar DNT scheme',
      'Complete application form',
      'Upload certificates',
      'Submit application',
    ],
    tips: [
      'For Denotified Nomadic Tribes specifically',
      'Jan Aadhaar is mandatory for all Rajasthan scholarships',
    ],
    description: 'Rajasthan Ambedkar DNT scholarship supports students from Denotified and Nomadic Tribe communities.',
    tags: ['rajasthan', 'dnt', 'sc', 'st', 'post-matric'],
    isActive: true,
  },

  // ==================== WEST BENGAL ====================
  {
    title: 'West Bengal Oasis Scholarship — SC/ST/OBC',
    provider: 'Backward Classes Welfare Department, West Bengal',
    providerType: 'State Government',
    eligibility: {
      states: ['West Bengal'],
      categories: ['SC', 'ST', 'OBC'],
      incomeLimit: 250000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 10000,
    amountDesc: 'Up to ₹10,000 per year',
    deadline: 'December 31 every year',
    applicationLink: 'https://oasis.gov.in',
    documentsRequired: [
      'Caste certificate from West Bengal',
      'Income certificate',
      'Aadhaar card',
      'West Bengal domicile',
      'Marksheet',
      'Bank details',
    ],
    applicationSteps: [
      'Visit oasis.gov.in',
      'Register as new student',
      'Fill application form',
      'Upload all documents',
      'Submit for institution verification',
    ],
    tips: [
      'OASIS is the dedicated portal for WB scholarships',
      'Institution must verify online',
      'Apply in September when portal opens',
    ],
    description: 'West Bengal OASIS portal scholarship for SC, ST and OBC students with income below ₹2.5 lakh.',
    tags: ['west-bengal', 'state', 'sc', 'st', 'obc', 'oasis'],
    isActive: true,
  },
  {
    title: 'West Bengal Aikyashree Scholarship — Minority',
    provider: 'Minority Affairs Department, West Bengal',
    providerType: 'State Government',
    eligibility: {
      states: ['West Bengal'],
      categories: ['Muslim', 'Christian', 'Sikh', 'Buddhist', 'Jain', 'Parsi'],
      incomeLimit: 200000,
      courseLevels: ['Class 1', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 50,
    },
    amount: 10000,
    amountDesc: 'Up to ₹10,000 per year for minority students',
    deadline: 'November 30 every year',
    applicationLink: 'https://wbmdfcscholarship.in',
    documentsRequired: [
      'Minority community certificate',
      'Income certificate',
      'Aadhaar card',
      'WB domicile',
      'Marksheet',
      'School or college bonafide',
    ],
    applicationSteps: [
      'Visit wbmdfcscholarship.in',
      'Register with details',
      'Fill Aikyashree scholarship form',
      'Upload minority certificate and documents',
      'Submit before deadline',
    ],
    tips: [
      'Aikyashree is specifically for WB minority students',
      'Available from Class 1 to postgraduate',
      'Income limit is ₹2 lakh per year',
    ],
    description: 'West Bengal Aikyashree scholarship supports minority community students at all levels of education.',
    tags: ['west-bengal', 'minority', 'all-levels', 'state'],
    isActive: true,
  },
  {
    title: 'Swami Vivekananda Merit Cum Means Scholarship — WB',
    provider: 'Higher Education Department, West Bengal',
    providerType: 'State Government',
    eligibility: {
      states: ['West Bengal'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 250000,
      courseLevels: ['Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 75,
    },
    amount: 60000,
    amountDesc: 'Up to ₹60,000 per year — one of highest state scholarships',
    deadline: 'October 31 every year',
    applicationLink: 'https://svmcm.wbhed.gov.in',
    documentsRequired: [
      'Class 12 marksheet showing 75% or above',
      'Income certificate below ₹2.5 lakh',
      'WB domicile',
      'Aadhaar card',
      'College admission proof',
      'Bank details',
    ],
    applicationSteps: [
      'Visit svmcm.wbhed.gov.in',
      'Register with Class 12 roll number',
      'Complete application form',
      'Upload documents',
      'College must verify application',
    ],
    tips: [
      'One of highest state scholarship amounts in India',
      'Need 75% or above in Class 12',
      'Both merit and income criteria apply',
      'Very competitive — apply early',
    ],
    description: 'Swami Vivekananda Merit Cum Means Scholarship provides up to ₹60,000 per year to meritorious students in West Bengal — among the highest state scholarships in India.',
    tags: ['west-bengal', 'merit', 'high-amount', 'undergraduate', 'postgraduate'],
    isActive: true,
  },

  // ==================== TAMIL NADU ====================
  {
    title: 'Tamil Nadu Post Matric Scholarship — BC/MBC',
    provider: 'Adi Dravidar and Tribal Welfare Department, Tamil Nadu',
    providerType: 'State Government',
    eligibility: {
      states: ['Tamil Nadu'],
      categories: ['BC', 'MBC', 'OBC'],
      incomeLimit: 200000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 15000,
    amountDesc: 'Up to ₹15,000 per year',
    deadline: 'October 31 every year',
    applicationLink: 'https://scholarships.gov.in',
    documentsRequired: [
      'Community certificate from Tamil Nadu',
      'Income certificate',
      'Aadhaar card',
      'Nativity certificate TN',
      'Marksheet',
      'Bank details',
    ],
    applicationSteps: [
      'Apply through NSP scholarships.gov.in',
      'Select Tamil Nadu BC MBC scholarship',
      'Fill complete form',
      'Upload community and income certificate',
      'Submit before deadline',
    ],
    tips: [
      'Community certificate must be from Tamil Nadu',
      'Nativity certificate is mandatory',
      'Apply through NSP portal',
    ],
    description: 'Tamil Nadu Post Matric Scholarship for Backward Class and Most Backward Class students with income below ₹2 lakh.',
    tags: ['tamil-nadu', 'obc', 'bc', 'mbc', 'post-matric', 'state'],
    isActive: true,
  },
  {
    title: 'Tamil Nadu Chief Minister Girl Student Scholarship',
    provider: 'Government of Tamil Nadu',
    providerType: 'State Government',
    eligibility: {
      states: ['Tamil Nadu'],
      categories: ['General', 'BC', 'MBC', 'SC', 'ST'],
      incomeLimit: 0,
      courseLevels: ['Undergraduate'],
      genderSpecific: 'Girls Only',
      minMarks: 60,
    },
    amount: 1000,
    amountDesc: '₹1,000 per month for girl students in government colleges',
    deadline: 'August 31 every year',
    applicationLink: 'https://www.tn.gov.in',
    documentsRequired: [
      'Aadhaar card',
      'TN nativity certificate',
      'Class 12 marksheet',
      'College admission in government college',
      'Bank details',
    ],
    applicationSteps: [
      'Apply through college after admission',
      'Submit documents to college office',
      'College forwards to government',
      'Amount credited directly to bank',
    ],
    tips: [
      'Only for students in Tamil Nadu government colleges',
      'No income limit for this scholarship',
      'Apply through your college directly',
      'Monthly payment of ₹1,000',
    ],
    description: 'Tamil Nadu Chief Minister scholarship provides ₹1,000 per month to girl students studying in government colleges regardless of income.',
    tags: ['tamil-nadu', 'girls-only', 'monthly', 'government-college', 'no-income-limit'],
    isActive: true,
  },
  {
    title: 'Tamil Nadu SC/ST Scholarship — Higher Education',
    provider: 'Adi Dravidar and Tribal Welfare Dept, Tamil Nadu',
    providerType: 'State Government',
    eligibility: {
      states: ['Tamil Nadu'],
      categories: ['SC', 'ST'],
      incomeLimit: 250000,
      courseLevels: ['Undergraduate', 'Postgraduate', 'Professional'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 25000,
    amountDesc: 'Up to ₹25,000 per year for professional courses',
    deadline: 'November 30 every year',
    applicationLink: 'https://scholarships.gov.in',
    documentsRequired: [
      'SC/ST community certificate TN',
      'Income certificate',
      'TN nativity certificate',
      'Aadhaar card',
      'Marksheet',
      'Fee receipts',
    ],
    applicationSteps: [
      'Apply on NSP portal',
      'Select Tamil Nadu SC/ST scholarship',
      'Attach community certificate',
      'Upload all documents',
      'Submit before deadline',
    ],
    tips: [
      'Higher amounts for professional courses like MBBS and engineering',
      'Apply every year for renewal',
      'Keep community certificate updated',
    ],
    description: 'Tamil Nadu SC/ST scholarship for higher education including professional courses like medicine and engineering.',
    tags: ['tamil-nadu', 'sc', 'st', 'professional', 'engineering', 'medical'],
    isActive: true,
  },

  // ==================== MADHYA PRADESH ====================
  {
    title: 'MP Post Matric Scholarship — SC/ST/OBC',
    provider: 'Tribal Affairs Department, Government of MP',
    providerType: 'State Government',
    eligibility: {
      states: ['Madhya Pradesh'],
      categories: ['SC', 'ST', 'OBC'],
      incomeLimit: 600000,
      courseLevels: ['Class 11', 'Class 12', 'Undergraduate', 'Postgraduate'],
      genderSpecific: 'All',
      minMarks: 0,
    },
    amount: 15000,
    amountDesc: 'Up to ₹15,000 per year',
    deadline: 'November 15 every year',
    applicationLink: 'https://scholarshipportal.mp.nic.in',
    documentsRequired: [
      'Samgra ID (mandatory for MP)',
      'Caste certificate',
      'Income certificate',
      'Aadhaar card',
      'Marksheet',
      'Bank details',
    ],
    applicationSteps: [
      'Get your Samgra ID first',
      'Visit scholarshipportal.mp.nic.in',
      'Login with Samgra ID',
      'Fill scholarship application',
      'Upload documents',
      'Submit before deadline',
    ],
    tips: [
      'Samgra ID is mandatory — get it first from MP govt',
      'Higher income limit of ₹6 lakh for OBC',
      'Portal opens every July',
    ],
    description: 'Madhya Pradesh Post Matric Scholarship for SC, ST and OBC students — requires Samgra ID unique to MP.',
    tags: ['madhya-pradesh', 'sc', 'st', 'obc', 'post-matric', 'state'],
    isActive: true,
  },
  {
    title: 'MP Gaon Ki Beti Scholarship',
    provider: 'Higher Education Department, Madhya Pradesh',
    providerType: 'State Government',
    eligibility: {
      states: ['Madhya Pradesh'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 0,
      courseLevels: ['Undergraduate'],
      genderSpecific: 'Girls Only',
      minMarks: 60,
    },
    amount: 5000,
    amountDesc: '₹500 per month for 10 months per year',
    deadline: 'August 31 every year',
    applicationLink: 'https://scholarshipportal.mp.nic.in',
    documentsRequired: [
      'Samgra ID',
      'Class 12 marksheet with 60% or above',
      'Village residence proof',
      'Aadhaar card',
      'Bank details',
    ],
    applicationSteps: [
      'Login to MP scholarship portal with Samgra ID',
      'Select Gaon Ki Beti scheme',
      'Upload Class 12 marksheet',
      'Provide village domicile proof',
      'Submit application',
    ],
    tips: [
      'For girls from rural villages only — not cities',
      'Must have scored 60% or above in Class 12',
      'No income limit for this scheme',
      'Samgra ID mandatory',
    ],
    description: 'Gaon Ki Beti scholarship supports girl students from rural villages of MP scoring 60% or above in Class 12 with ₹500 per month.',
    tags: ['madhya-pradesh', 'girls-only', 'rural', 'village', 'monthly', 'no-income-limit'],
    isActive: true,
  },
  {
    title: 'MP Pratibha Kiran Scholarship — Urban Girls',
    provider: 'Higher Education Department, Madhya Pradesh',
    providerType: 'State Government',
    eligibility: {
      states: ['Madhya Pradesh'],
      categories: ['General', 'OBC', 'SC', 'ST'],
      incomeLimit: 0,
      courseLevels: ['Undergraduate'],
      genderSpecific: 'Girls Only',
      minMarks: 60,
    },
    amount: 5000,
    amountDesc: '₹500 per month for 10 months — for urban girls',
    deadline: 'August 31 every year',
    applicationLink: 'https://scholarshipportal.mp.nic.in',
    documentsRequired: [
      'Samgra ID',
      'Class 12 marksheet 60% or above',
      'BPL card or income proof',
      'Urban residence proof',
      'Aadhaar card',
    ],
    applicationSteps: [
      'Login to MP scholarship portal',
      'Select Pratibha Kiran scheme',
      'Upload BPL card and marksheet',
      'Submit with Samgra ID',
    ],
    tips: [
      'Specifically for urban girls from BPL families',
      'Companion scheme to Gaon Ki Beti for city girls',
      'Must be from BPL family in urban area',
    ],
    description: 'MP Pratibha Kiran scholarship for girl students from urban BPL families scoring 60% or above in Class 12.',
    tags: ['madhya-pradesh', 'girls-only', 'urban', 'bpl', 'monthly'],
    isActive: true,
  },
]

const stories = [
  {
    displayName: 'Priya S.',
    isAnonymous: false,
    avatar: '🌸',
    location: { city: 'Sikar', state: 'Rajasthan' },
    course: 'B.Tech Computer Science',
    year: '3rd Year',
    background: 'First in my family to pursue engineering. My father is a farmer, my mother never went to school.',
    storyText: `I still remember the day I got my JEE result. I had qualified for a private college but the fees were ₹1.2 lakh per year. My father looked at the number and went silent. I thought my dream was over before it started.

A friend told me about KAIROS. I was skeptical — I had tried other websites and they all felt like they were made for someone else, not for a girl from Sikar. But KAI was different. She didn't make me feel like I was asking stupid questions.

She found the AICTE Pragati scholarship for me. ₹50,000 per year, specifically for girls in technical colleges. I didn't even know it existed. KAI walked me through every document, every step. When I panicked about the income certificate, she told me exactly which office to go to and what to ask for.

I'm now in my third year. My fees are covered. I'm the first engineer in my family.

If you're reading this and you think you can't afford it — please talk to KAI first. There is money out there for you. You just need someone to help you find it.`,
    tags: ['Scholarship Winner', 'Engineering', 'Small Town', 'First in Family'],
    likes: 1247,
    isPublished: true,
    isSeed: true,
  },
  {
    displayName: 'Anjali M.',
    isAnonymous: false,
    avatar: '🌻',
    location: { city: 'Yavatmal', state: 'Maharashtra' },
    course: 'BSc Nursing',
    year: 'Final Year',
    background: 'My parents were planning my marriage after Class 12.',
    storyText: `In my family, girls study till 12th and then get married. That's just how it was. I had seen my older sister go through it. I didn't want that for myself — I wanted to work, to earn, to be someone. But I didn't know how to say this without hurting my family.

I found KAIROS at 1am one night when I couldn't sleep. I typed my whole situation to KAI — the marriage pressure, my nursing dream, my father's fear that education would ruin me. KAI didn't judge any of it. She just listened.

Then she helped me build a plan. She showed me the salary a staff nurse earns in Maharashtra government hospitals. She found colleges in Nagpur and Aurangabad with low fees. She helped me calculate exactly how much I would earn and how quickly I could support my family.

When I showed my parents these numbers, something shifted. My father said — if she can support herself and help us, why would we stop her?

I'm in my final year now. I have a government hospital internship lined up. My parents come to my college functions with pride.

KAI didn't just help me find a course. She helped me find the words to fight for my own life.`,
    tags: ['Family Pressure', 'Career Change', 'Nursing', 'First in Family'],
    likes: 2103,
    isPublished: true,
    isSeed: true,
  },
  {
    displayName: 'Anonymous',
    isAnonymous: true,
    avatar: '⭐',
    location: { city: 'Muzaffarpur', state: 'Bihar' },
    course: 'BA Political Science',
    year: '2nd Year',
    background: 'I scored 71% in 12th and everyone told me I was not good enough.',
    storyText: `71%. That's what I scored in my Class 12 boards. My relatives said she's not smart enough for proper college. My teacher suggested I do a basic diploma. Even I started believing them.

I almost didn't apply anywhere. Then a friend shared KAIROS with me.

I was embarrassed to even type my marks. But KAI — she didn't react the way I expected. She said something I'll never forget: 71% is not your ceiling. It's just your starting point. Let me show you what's possible.

She found BA programs at universities in Patna that accepted my marks. She told me about the Post Matric Scholarship for which I qualified. She explained what Political Science actually leads to — civil services, law, journalism — things I had never connected to my interest in politics.

I'm studying in Patna now. I received ₹23,000 in scholarship this year. I'm applying for UPSC CSE in 2 years.

Please don't let anyone's words become the story you believe about yourself.`,
    tags: ['Average Marks', 'UPSC Dream', 'Scholarship Winner', 'Self Belief'],
    likes: 3412,
    isPublished: true,
    isSeed: true,
  },
]

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI)
    console.log('✅ Connected to MongoDB')

    await Scholarship.deleteMany({})
    await Story.deleteMany({ isSeed: true })
    console.log('✅ Cleared existing data')

    await Scholarship.insertMany(scholarships)
    console.log(`✅ Seeded ${scholarships.length} scholarships`)

    await Story.insertMany(stories)
    console.log(`✅ Seeded ${stories.length} stories`)

    console.log('🎉 Day 1 states seeded — All India + UP + Maharashtra + Bihar + Rajasthan + West Bengal + Tamil Nadu + MP')
    process.exit(0)
  } catch (error) {
    console.error('❌ Seed error:', error)
    process.exit(1)
  }
}

seed()